### ISSUE TITLE
[TASK-222] 아코디언 만들기

### ISSUE THREAD

**Issue by kd02109** [ToyVallet/swifty-frontend#28]
- 아코디언 컴포넌트를 구현합니다.
- UI 요소로 다른 프로젝트에서 활용할 수 있도록 공통 컴포넌트를 구현합니다.
- 회원가입 페이지의 약관동의에 해당 컴포넌트를 도입합니다.

**Comment by ho991217** [comment]
아코디언 컴포넌트가 아니라서, 닫도록 하겠습니다~
